# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/
#theme = "congo"
baseURL = "https://mihohoi0322.github.io/"
defaultContentLanguage = "en"
enableRobotsTXT = true
paginate = 10
summaryLength = 0

# GitHub
publishDir = "docs"
canonifyurls = true
[outputs]
  home = ["HTML", "RSS", "JSON"]
